// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package plugin.sqlconn.sql_conn

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SqlConnApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class SqlConnectionConfig (
  val connectionId: String,
  val host: String,
  val port: Long,
  val database: String,
  val username: String,
  val password: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SqlConnectionConfig {
      val connectionId = pigeonVar_list[0] as String
      val host = pigeonVar_list[1] as String
      val port = pigeonVar_list[2] as Long
      val database = pigeonVar_list[3] as String
      val username = pigeonVar_list[4] as String
      val password = pigeonVar_list[5] as String
      return SqlConnectionConfig(connectionId, host, port, database, username, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      connectionId,
      host,
      port,
      database,
      username,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SqlConnectionConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return SqlConnApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class SqlConnApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SqlConnectionConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SqlConnectionConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SqlConnHostApi {
  fun connect(config: SqlConnectionConfig, callback: (Result<Boolean>) -> Unit)
  fun disconnect(connectionId: String, callback: (Result<Boolean>) -> Unit)
  fun read(connectionId: String, query: String, params: List<Any?>?, callback: (Result<List<Map<Any?, Any?>>>) -> Unit)
  fun write(connectionId: String, query: String, params: List<Any?>?, callback: (Result<Long>) -> Unit)
  fun callProcedure(connectionId: String, procedureName: String, params: List<Any?>?, callback: (Result<List<Map<Any?, Any?>>>) -> Unit)
  fun executeScript(connectionId: String, script: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by SqlConnHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SqlConnApiPigeonCodec()
    }
    /** Sets up an instance of `SqlConnHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SqlConnHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sql_conn.SqlConnHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as SqlConnectionConfig
            api.connect(configArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SqlConnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SqlConnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sql_conn.SqlConnHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val connectionIdArg = args[0] as String
            api.disconnect(connectionIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SqlConnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SqlConnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sql_conn.SqlConnHostApi.read$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val connectionIdArg = args[0] as String
            val queryArg = args[1] as String
            val paramsArg = args[2] as List<Any?>?
            api.read(connectionIdArg, queryArg, paramsArg) { result: Result<List<Map<Any?, Any?>>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SqlConnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SqlConnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sql_conn.SqlConnHostApi.write$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val connectionIdArg = args[0] as String
            val queryArg = args[1] as String
            val paramsArg = args[2] as List<Any?>?
            api.write(connectionIdArg, queryArg, paramsArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SqlConnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SqlConnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sql_conn.SqlConnHostApi.callProcedure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val connectionIdArg = args[0] as String
            val procedureNameArg = args[1] as String
            val paramsArg = args[2] as List<Any?>?
            api.callProcedure(connectionIdArg, procedureNameArg, paramsArg) { result: Result<List<Map<Any?, Any?>>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SqlConnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SqlConnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sql_conn.SqlConnHostApi.executeScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val connectionIdArg = args[0] as String
            val scriptArg = args[1] as String
            api.executeScript(connectionIdArg, scriptArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SqlConnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SqlConnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
